version: '3.7'

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    image: ajitmen/tweetit:v0.1 
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always   
    networks: 
      - tweetnw

  # Frontend Service 
  app-client:
    image: ajitmen/tweetit-ui:v0.1
    ports:
      - "80:80" # Map the exposed port 80 on the container to port 9090 on the host machine
    restart: always
    depends_on:
      - app-server
    networks:
      - tweetnw  



# Networks to be created to facilitate communication between containers
networks:
  tweetnw:  
